### ISSUE TITLE
How to inject the custom badge file in 1.3.1 version 

### ISSUE THREAD

**Issue by Ward777** [AntiMach/Simple_badge_injector#2]
The current tutorial says: "Select File > Save data to... and navigate to the root of your SD card and create a new folder called Badge Files"
Since most of the tut are outdated, I am wording how to inject the custom badge file in 1.3.1 version?

Thanks in advance.

**Comment by AntiMach** [comment]
Yeah, I forgot to update the tutorials, but the place to save these is now on the "/3ds/SimpleBadgeInjector/" folder, and not in the "/Badge Files" folder. The dumped data is saved on "/3ds/SimpleBadgeInjector/Dumped".
