### ISSUE TITLE
"Failed to write to ExtData archive" and "Failed to delete ExtData archive"

### ISSUE THREAD

**Issue by einso** [AntiMach/Simple_badge_injector#3]
Hi! I have followed the instructions as posted on [this thread](https://gbatemp.net/threads/get-any-official-badges-without-other-users-data.476300/), and am running into issues at the last step when injecting the custom badge files.

The files are located in /3ds/SimpleBadgeInjector on my SD card, and when attempting to inject them, I get a message "Failed to write to ExtData archive". It is also not possible for me to delete and create a new ExtData archive, as I simply get "Failed to delete ExtData archive" when attempting to delete.

I am not 100% certain as to how to troubleshoot this any further. My unique badge count is at 410, the total badges at 104550, so I should not be running into issues with the badge limit as far as I am aware. One idea I have is that it might be related to importing JPN badges to EUR data sets, but I'm not certain. Nevertheless, that shouldn't be causing an issue with deleting the ExtData archive.

Please let me know if you have any ideas as to how to fix these, or how I can be of support with troubleshooting this.

**Comment by XxSIBxX** [comment]
Try using the CIA file instead, the 3dsx file seems to have issues.

(Sorry for replying to this old thread, meant this to help any other people who run into this issue and see this as well)

**Comment by ryumiyax** [comment]
> Try using the CIA file instead, the 3dsx file seems to have issues.
> 
> (Sorry for replying to this old thread, meant this to help any other people who run into this issue and see this as well)

我遇到了和他基本一模一样的问题，无法删除、创建、或者注入备份的数据，甚至是我刚刚为自己备份的数据，而且我使用的就是CIA文件的版本
请问你能否提供一下你的操作步骤呢？

I encountered basically the same problem as them. I couldn't delete, create, or inject backed up data, even the data I just backed up from itself, and I was using the version of the CIA file.
Could you please provide me with your steps?

**Comment by ryumiyax** [comment]
仔细阅读了一遍相关部分的代码，我发现我搞错了一件很蠢的事
`.dat`文件应该放在`sd:/3ds/SimpleBadgeInjector/`下而不是`sd:/3ds/SimpleBadgeInjector/Dumped`下来进行恢复

After reading the relevant part of the code carefully, I found that I made a stupid mistake.
`.dat`The file should be placed under `sd:/3ds/SimpleBadgeInjector/` instead of `sd:/3ds/SimpleBadgeInjector/Dumped` for recovery
